default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  host: localhost

  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: pb_development

test:
  <<: *default
  database: pb

production:
  <<: *default
  database: solana_production
  username: port
  password: <%= ENV['SOLANA_DATABASE_PASSWORD'] %>

